### ISSUE TITLE
When I run this project,the segmentation fault (core dump) is always happening

### ISSUE THREAD

**Issue by BigRayLee** [yaoxt3/lidarnode#1]
`##############################

Failed to find match for field 'intensity'.

##############################

frame_id:68

Segmentation fault (core dumped)

`

**Comment by yaoxt3** [comment]
What is the final output of the program, the frame_id is 68 indicating that the program has run successfully,  maybe your LiDAR bag has some problem.

**Comment by BigRayLee** [comment]
The final output is the last frame_id number. And the number is randomly when the segmentation fault has happened. And I check the code,I found when it run this 
`if(frame_id >= max_frame && nocluster == false)
{
                
 vector<frame_info >::iterator it = frame_points.begin();
		frame_points.erase(it);
		for (int i = 0; i < max_frame-1; ++i) {
			frame_points[i] = frame_points[i+1];
		}
}
`
the last frame_id only looped 8 times.
![78931955](https://user-images.githubusercontent.com/30024514/49000318-1f74c400-f194-11e8-8099-49a2b6446b67.jpg)

**Comment by BigRayLee** [comment]
I changed some code,let the id=frame_id-1;And the problem has been solved. And there is another problem, when I run the this program and visualized it in rviz,  I found that a cluster of particles appeared at the origin of the coordinate.I don't think there is any problem with the project. I don't know where they came from.
![screenshot from 2018-11-26 18-53-39](https://user-images.githubusercontent.com/30024514/49010219-7d61d580-f1ad-11e8-826f-dbb55dbcb33c.png)

**Comment by yaoxt3** [comment]
What do you want to do through this project code? Want to know about particle filter? This code has not been maintained for a long time, maybe I've solved the problems you're encountered, but the functions implemented in the final version are quite different from this project, I can give you a sample that using particle filter to tracking a walking person with LiDAR.

**Comment by BigRayLee** [comment]
Thank you for your answer. I am learning the particle filter now, and your code help a lot. In my last comments, I am trying to track multi obstacles, maybe this is the problem. And you mentioned the sample about using particle filter to track a walking person, the sample means a rosbag or somenthing?

**Comment by yaoxt3** [comment]
The source code and test rosbag, you can give me your email, and I'll send it to you.

**Comment by BigRayLee** [comment]
Thank you, my email is ragelee@foxmail.com.
